const ordo = [
  {
    avgRating: null,
    listingBathroomLabel: "2 baths",
    bathrooms: 2,
    listingBedLabel: "10 beds",
    bedrooms: 4,
    beds: 10,
    businessHostLabel: null,
    city: "Bolivar Peninsula",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "10 guests",
    id: "740807800483774592",
    isAutoTranslated: false,
    isNewListing: true,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Bolivar Peninsula",
    localizedDistanceText: null,
    locationTitle: null,
    locationContext: null,
    listingName: "Sleeps 10 | Beach Access | Tiki Bar | Dog Friendly",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [
      "Wifi",
      "Self check-in",
      "Kitchen",
      "Air conditioning",
    ],
    previewTags: [],
    publicAddress: "Bolivar Peninsula, TX, United States",
    reviews: null,
    reviewsCount: 2,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: null,
    summary: null,
    wishlistedCount: null,
    title: "Home in Bolivar Peninsula",
    avgRatingLocalized: "New",
    accessibilityLabel: "$201 per night",
    concatQualifierLeft: false,
    price: "$201",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-01",
    checkout: "2022-12-06",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8662",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-740807800483774592/original/221e024f-9800-4ed8-9c36-b538101207f4.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-740807800483774592/original/6491cdaf-0dfa-46ad-b93a-a3f05382cbb1.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-740807800483774592/original/a913a420-953e-4741-ad4f-059dd3d9b91d.png?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-740807800483774592/original/27002407-70d1-418a-adff-5ac98789ebf6.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-740807800483774592/original/8e5abed0-4864-4370-bf60-fcf27af06bdb.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-740807800483774592/original/9a0f8484-2691-4578-aa1e-e67a491b6483.png?im_w=720",
    ],
  },
  {
    avgRating: 4.88,
    listingBathroomLabel: "2 baths",
    bathrooms: 2,
    listingBedLabel: "5 beds",
    bedrooms: 3,
    beds: 5,
    businessHostLabel: null,
    city: "Inglis",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "8 guests",
    id: "46775194",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Inglis",
    localizedDistanceText: "1,052 miles",
    locationTitle: "Inglis, Manitoba",
    locationContext: null,
    listingName: "Rare Lakefront Shipping Container Near Asessippi",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Inglis, MB, Canada",
    reviews: [],
    reviewsCount: 97,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Cabin",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Inglis, Canada",
    avgRatingLocalized: "4.88",
    accessibilityLabel: "$212 per night",
    concatQualifierLeft: false,
    price: "$212",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-01",
    checkout: "2022-12-07",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-46775194/original/05b2184c-2350-4316-8f4a-893342d9f3cf.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/2a1ef0d3-1427-4f9c-a2ff-82e822caf39d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e8d2fb88-019a-42db-919b-e007f9c11eea.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/902f6bb4-b3ec-4dd6-a74d-ecbb8008aad9.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/59613574-9922-4f28-a681-d3ba4f331cd3.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46775194/original/a1994e3a-dd5f-4f4d-ad1e-738af141578d.jpeg?im_w=720",
    ],
  },
  {
    avgRating: 4.77,
    listingBathroomLabel: "1 bath",
    bathrooms: 1,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Bolzano",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "4 guests",
    id: "4594196",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Bolzano",
    localizedDistanceText: "5,496 miles",
    locationTitle: "Bolzano, Trentino-Alto Adige/South Tyrol",
    locationContext: null,
    listingName: "Mirror House Sud",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Bolzano, Trentino-Alto Adige/South Tyrol, Italy",
    reviews: [],
    reviewsCount: 43,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Bolzano, Italy",
    avgRatingLocalized: "4.77",
    accessibilityLabel: "$259 per night",
    concatQualifierLeft: false,
    price: "$259",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-13",
    checkout: "2022-12-18",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/74102172/9815f41f_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/74102421/46d207f2_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/309bee53-311d-4f07-a2e7-14daadbbfb77.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/57807707/e0b2123a_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/74102480/7186bb11_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/57807675/c058832a_original.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.98,
    listingBathroomLabel: "3.5 baths",
    bathrooms: 3.5,
    listingBedLabel: "5 beds",
    bedrooms: 4,
    beds: 5,
    businessHostLabel: null,
    city: "Malibu",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "8 guests",
    id: "34577812",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Malibu",
    localizedDistanceText: "820 miles",
    locationTitle: "Malibu, California",
    locationContext: null,
    listingName: "Malibu Mid-Century Modern Luxury retreat home",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Malibu, CA, United States",
    reviews: [],
    reviewsCount: 102,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Malibu, California",
    avgRatingLocalized: "4.98",
    accessibilityLabel: "$1,255 per night",
    concatQualifierLeft: false,
    price: "$1,255",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-01",
    checkout: "2022-12-06",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/8255bdb1-1d65-4325-a744-6487dc51453b.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/1aed8660-0a2c-4ecd-bdfc-e2d0217e2a4b.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-34577812/original/abeb8e1c-b2e8-4a09-9a7a-eb2584c6fef9.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-34577812/original/8b0bb13c-9a61-4cee-9882-9c177473124b.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/8e062776-e4d5-4a27-a3d7-7e59f8eb7521.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/01b22bc4-4ce5-49ee-a52b-c9da6a86203c.jpg?im_w=720",
    ],
  },
  {
    avgRating: null,
    listingBathroomLabel: "7 baths",
    bathrooms: 7,
    listingBedLabel: "5 beds",
    bedrooms: 5,
    beds: 5,
    businessHostLabel: null,
    city: "Korčula",
    configurableContent: null,
    contextualPicturesPageInfo: null,
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "10 guests",
    id: "34594127",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Korčula",
    localizedDistanceText: "5,845 miles",
    locationTitle: "Korčula, Split Riviera",
    locationContext: null,
    listingName: "Villa Korcula Diamond",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: ["Pool", "Sun loungers", "Sound system"],
    previewTags: [],
    publicAddress: "Korčula, Split Riviera, Croatia",
    reviews: null,
    reviewsCount: 1,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: null,
    summary: null,
    wishlistedCount: null,
    title: "Korčula, Croatia",
    avgRatingLocalized: null,
    accessibilityLabel: "$3,420 per night",
    concatQualifierLeft: false,
    price: "$3,420",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-04",
    checkout: "2022-12-10",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/397ed026-16a9-4418-af19-1d2b31fe0aa8.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/2d7125a0-79ca-44ba-8ba5-d8b98a41092f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/dc3b21a8-e9b5-4aa4-b59c-be2766386dba.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/929bb70a-a677-4b8d-9848-3bb428e12dd8.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4576e133-fb6f-4cdc-8f59-c610643b7811.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e7ae179b-5642-4497-8b89-98271babbd2d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/fec6f091-9f3c-49bb-8dcf-cbb1f6bc47e6.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/db5d3f47-e338-4268-9591-a394d57af21f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/62187b83-7654-4c62-bde4-87cbe76ea757.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/98b42664-0661-4884-9fee-063993c9b62f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/36910409-a0d5-4755-b6f5-0323750a87f1.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/6c56017c-07c3-46b7-aead-98f3d06ab149.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ca0d7536-ec27-4e37-91fd-a46e8e20244f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/601a7097-e9bc-4cce-ae22-14cfa7cd280a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/13999019-dc78-4634-9b9c-af9e41822125.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/bd2e3568-0468-48a2-a1a5-d6332eecde3d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/312fe90d-004e-4081-abc8-8eced527917d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/bf32aa2b-a3a6-4800-9a40-ac24d0a9b8a5.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/1bca7f15-7fe2-422b-b78e-c87fc39a07ab.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/2df95748-0258-4ddc-8f23-181d1d5d119b.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e8e79ca3-4287-4726-a8fd-58bbbe071b2f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8b86c0bb-b4ed-416d-bd55-3f197a1ceb0c.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/f374a7c1-5c69-454f-beab-9de5c6d31ee7.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/af74aa06-b883-41bc-a013-74f26d641fba.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/344637b9-a5dd-4845-9d19-bb7503e679da.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/df9c3338-f451-4ab1-b22d-15a65eb99ed1.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/5ae0b75e-6138-43bd-9c43-d9e2fc7c4409.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.94,
    listingBathroomLabel: "3.5 baths",
    bathrooms: 3.5,
    listingBedLabel: "4 beds",
    bedrooms: 3,
    beds: 4,
    businessHostLabel: null,
    city: "Kamuela",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "6 guests",
    id: "17588844",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Kamuela",
    localizedDistanceText: "2,572 miles",
    locationTitle: "Kamuela, Hawaii",
    locationContext: null,
    listingName: "FLW-Hawaii's Only Frank Lloyd Wright Home!",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Kamuela, HI, United States",
    reviews: [],
    reviewsCount: 16,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Kamuela, Hawaii",
    avgRatingLocalized: "4.94",
    accessibilityLabel: "$950 per night",
    concatQualifierLeft: false,
    price: "$950",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-04-10",
    checkout: "2023-04-15",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/e19f8936-395d-4be2-90ac-b6b4f67f512a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/7ac47159-795a-4fb5-b9bb-86f8311cc63c.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/6c0df85a-45a1-420f-b594-01e2e05f0136.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ac2a07c7-37c6-4a69-bfdf-627378fc201d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/192de27d-1970-4359-8a17-11d46419e6d8.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/77e5b213-85f2-4309-8c8f-570bb01e73fd.jpg?im_w=720",
    ],
  },
  {
    avgRating: null,
    listingBathroomLabel: "3 baths",
    bathrooms: 3,
    listingBedLabel: "3 beds",
    bedrooms: 3,
    beds: 3,
    businessHostLabel: null,
    city: "Joshua Tree",
    configurableContent: null,
    contextualPicturesPageInfo: null,
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "6 guests",
    id: "53719772",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Joshua Tree",
    localizedDistanceText: "857 miles",
    locationTitle: "Joshua Tree, California",
    locationContext: null,
    listingName: "The Kellogg Doolittle House",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: ["Golf cart", "Sonos sound system", "Hot tub"],
    previewTags: [],
    publicAddress: "Joshua Tree, CA, United States",
    reviews: null,
    reviewsCount: 2,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Villa",
    starRating: null,
    summary: null,
    wishlistedCount: null,
    title: "Joshua Tree, California",
    avgRatingLocalized: null,
    accessibilityLabel: "$9,500 per night",
    concatQualifierLeft: false,
    price: "$9,500",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-06",
    checkout: "2022-12-13",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/4ea/air/v2/pictures/1f6c495e-b877-4a48-9f2c-d8012f640166.jpg",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/81d3f240-67c7-439e-ad74-865730d24ef8",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/8f2af184-d619-4811-9f88-86c353292f29",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/befeaff9-db94-4ac7-bd84-b8428d0488cf",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/110ce1ab-697a-4efb-adf2-00e048496bbe",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/386e838a-fc58-420d-929f-2415a6bbb3bc",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/cd917d61-c934-4431-afff-f937d69bc550",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/28ca731f-a9a4-4791-b698-e32bb88fa251",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/0055a858-8c25-4d43-8d4f-30566c5ab8ab",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/c3420f8b-5adc-418e-9ca0-f351c6c8fcde",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/a89dc092-9db5-4b9c-be4e-9372c9a9762f",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/a071b3f9-3929-4096-9041-87995a8bff86",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/76f55ae4-bb98-4d7f-b752-42b8eb55c5b3",
      "https://a0.muscache.com/4ea/air/v2/pictures/monet/Luxury-53719772/original/99e3f381-74cf-4637-8952-92e6a457edf8",
    ],
  },
  {
    avgRating: 4.99,
    listingBathroomLabel: "1 bath",
    bathrooms: 1,
    listingBedLabel: "2 beds",
    bedrooms: 1,
    beds: 2,
    businessHostLabel: null,
    city: "Cortez",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "33513388",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Cortez",
    localizedDistanceText: "914 miles",
    locationTitle: "Cortez, Colorado",
    locationContext: null,
    listingName: "Private Sage Canyon Cliff House near Mesa Verde.",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Cortez, CO, United States",
    reviews: [],
    reviewsCount: 214,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Cabin",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Cortez, Colorado",
    avgRatingLocalized: "4.99",
    accessibilityLabel: "$321 per night",
    concatQualifierLeft: false,
    price: "$321",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-26",
    checkout: "2022-12-31",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/794e91e5-32f5-4605-932f-0622d65c0cda.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/02a6b6df-bb89-4721-ba7f-c703d94a99d4.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/9e30417a-672e-4fd2-8510-d64a5a081bc6.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/802bc522-f1ee-414d-b224-d8fccf45dd87.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4e989c54-4927-497b-a25b-9dfd365a9d18.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/d0f174f6-35fe-4969-98f0-c139973091d7.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.75,
    listingBathroomLabel: "3 baths",
    bathrooms: 3,
    listingBedLabel: "5 beds",
    bedrooms: 4,
    beds: 5,
    businessHostLabel: null,
    city: "El Port de la Selva",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "10 guests",
    id: "3524556",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "El Port de la Selva",
    localizedDistanceText: "5,515 miles",
    locationTitle: "El Port de la Selva, Catalonia",
    locationContext: null,
    listingName: "Sunflower House",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "El Port de la Selva, Catalonia, Spain",
    reviews: [],
    reviewsCount: 143,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "El Port de la Selva, Spain",
    avgRatingLocalized: "4.75",
    accessibilityLabel: "$363 per night",
    concatQualifierLeft: false,
    price: "$363",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-02-20",
    checkout: "2023-02-25",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8528",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-3524556/original/24e9b114-7db5-4fab-8994-bc16f263ad1d.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/81723679/e5e479c0_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/81723649/cb11466a_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/62155089/67d8d207_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/81723620/15e2c8cb_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/81723669/95b975f3_original.jpg?im_w=720",
    ],
  },
  {
    avgRating: 5,
    listingBathroomLabel: "10.5 baths",
    bathrooms: 10.5,
    listingBedLabel: "9 beds",
    bedrooms: 8,
    beds: 9,
    businessHostLabel: null,
    city: "Fife",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "16 guests",
    id: "37013228",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Fife",
    localizedDistanceText: "4,586 miles",
    locationTitle: "Fife, Scotland",
    locationContext: null,
    listingName: "Kinnettles Mansion",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Fife, Scotland, United Kingdom",
    reviews: [],
    reviewsCount: 22,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Castle",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Fife, UK",
    avgRatingLocalized: "5.0",
    accessibilityLabel: "$774 per night",
    concatQualifierLeft: false,
    price: "$774",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-07",
    checkout: "2022-12-13",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8047",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/8b29bbe1-fe0a-4a32-9dba-1af15dbde880.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/5d9c39cc-2f2d-4ac5-a5a7-b817757ae239.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4acf5848-3e7d-4866-bf9a-ed36ab335e38.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/df409169-55ee-4e66-aad4-b9c46f6ca2f1.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/ad906eb4-9108-4e47-bd60-a4122ba460e4.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-37013228/original/7a4cefb2-343d-43eb-8aa8-1302bf36fefa.jpeg?im_w=720",
    ],
  },
  {
    avgRating: 5,
    listingBathroomLabel: "7 baths",
    bathrooms: 7,
    listingBedLabel: "13 beds",
    bedrooms: 9,
    beds: 13,
    businessHostLabel: null,
    city: "Ovens",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "16 guests",
    id: "44443304",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Ovens",
    localizedDistanceText: "4,653 miles",
    locationTitle: "Ovens, County Cork",
    locationContext: null,
    listingName: "Elegant Manor House",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Ovens, County Cork, Ireland",
    reviews: [],
    reviewsCount: 5,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Castle",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Ovens, Ireland",
    avgRatingLocalized: "5.0",
    accessibilityLabel: "$1,140 per night",
    concatQualifierLeft: false,
    price: "$1,140",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-08",
    checkout: "2022-12-13",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8047",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/c0bfa170-68ac-4608-a279-93b567658446.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a4715256-4533-4b6b-aaee-936c7b704825.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/fa4f31a4-f40a-43ae-b428-83932e01a6e1.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/b242ff72-f375-4290-a752-5940a6368afc.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4c05dc6c-ecba-471b-930d-994eef730ad6.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/095355f4-9145-42c9-8510-28e9c3690387.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.95,
    listingBathroomLabel: "3 baths",
    bathrooms: 3,
    listingBedLabel: "5 beds",
    bedrooms: 3,
    beds: 5,
    businessHostLabel: null,
    city: "Perth",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "6 guests",
    id: "5908470",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Perth",
    localizedDistanceText: "4,569 miles",
    locationTitle: "Perth, Scotland",
    locationContext: null,
    listingName: "Balvaird Wing at Scone Palace",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Perth, Scotland, United Kingdom",
    reviews: [],
    reviewsCount: 44,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Apartment",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Perth, UK",
    avgRatingLocalized: "4.95",
    accessibilityLabel: "$480 per night",
    concatQualifierLeft: false,
    price: "$480",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-03",
    checkout: "2022-12-08",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8047",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/73596478/5d9458d1_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/73597042/92fa2089_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/73596942/fc81fda1_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/73596981/35e3ed8a_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/73597003/e1ba1f54_original.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/73596914/924298fc_original.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.94,
    listingBathroomLabel: "1 bath",
    bathrooms: 1,
    listingBedLabel: "1 bed",
    bedrooms: 0,
    beds: 1,
    businessHostLabel: null,
    city: "Government Camp",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "46524848",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Government Camp",
    localizedDistanceText: "47 miles",
    locationTitle: "Government Camp, Oregon",
    locationContext: null,
    listingName: "Cozy Studio with Private Hot Tub in Govy",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Government Camp, OR, United States",
    reviews: [],
    reviewsCount: 96,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Apartment",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Government Camp, Oregon",
    avgRatingLocalized: "4.94",
    accessibilityLabel: "$199 per night",
    concatQualifierLeft: false,
    price: "$199",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-01-08",
    checkout: "2023-01-13",
    relaxedAmenityIds: null,
    categoryTag: "Tag:5366",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/dd7395d5-c02e-48e2-a7dc-ba3021be5a94.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46524848/original/a5313fc3-0b4e-4501-8500-dab7dc5ffb70.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46524848/original/086d9638-aee3-4a3a-8364-51bf84844e71.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46524848/original/b77346cc-50cc-4eb9-aee9-a1111daffdac.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46524848/original/cc320088-3e6d-4c8f-9f71-08b0297dfe11.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46524848/original/887a7966-c200-4465-9b95-4151545db8dc.jpeg?im_w=720",
    ],
  },
  {
    avgRating: null,
    listingBathroomLabel: "8 baths",
    bathrooms: 8,
    listingBedLabel: "10 beds",
    bedrooms: 6,
    beds: 10,
    businessHostLabel: null,
    city: "Park City",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "16 guests",
    id: "48543973",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Park City",
    localizedDistanceText: "658 miles",
    locationTitle: "Park City, Utah",
    locationContext: null,
    listingName:
      "Holiday Availability! Luxury Mountain Home with Home Theater, Sauna and Hot Tub on Private Ski Run",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Park City, UT, United States",
    reviews: null,
    reviewsCount: 0,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: null,
    summary: null,
    wishlistedCount: null,
    title: "Park City, Utah",
    avgRatingLocalized: null,
    accessibilityLabel: "$1,519 per night",
    concatQualifierLeft: false,
    price: "$1,519",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-01",
    checkout: "2022-12-06",
    relaxedAmenityIds: null,
    categoryTag: "Tag:5366",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/dfc41b99-ffe4-42bd-bd65-89e4135c519e.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/7148d2a3-f058-413a-ae48-7a7e79487042.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/3946359c-d47e-4c9c-a81f-d8ad4232d0dd.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a3f89392-8a42-4b8b-8776-14f35e407f00.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/afd53d69-0b85-4861-a9d6-2453b0d9158c.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/d26fa4fe-8d62-4e6f-b1fd-2a33674a1672.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.95,
    listingBathroomLabel: "6 baths",
    bathrooms: 6,
    listingBedLabel: "14 beds",
    bedrooms: 8,
    beds: 14,
    businessHostLabel: null,
    city: "Mountain Village",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "16 guests",
    id: "29735400",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Mountain Village",
    localizedDistanceText: "924 miles",
    locationTitle: "Mountain Village, Colorado",
    locationContext: null,
    listingName: "Spectacular 8-Bedroom Ski-in/Ski-out Luxury Home",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Mountain Village, CO, United States",
    reviews: [],
    reviewsCount: 21,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Mountain Village, Colorado",
    avgRatingLocalized: "4.95",
    accessibilityLabel: "$1,135 per night",
    concatQualifierLeft: false,
    price: "$1,135",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-10",
    checkout: "2022-12-15",
    relaxedAmenityIds: null,
    categoryTag: "Tag:5366",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/de887b25-18e5-4a3f-bf70-c2a4b85505a3.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/b208ad3f-4e93-432c-8ffd-abc1eb0b7d55.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4f1d17c4-0912-4e22-b2e0-082c4e2902d3.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/43036ddb-5d91-420a-8da3-35ce3e70d67d.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/aa2ccc70-aba0-4cfc-bf8e-42ae3cc4fe01.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/bddde899-3598-49de-b720-b51141ad4c93.jpg?im_w=720",
    ],
  },
  {
    avgRating: 5,
    listingBathroomLabel: "3 baths",
    bathrooms: 3,
    listingBedLabel: "12 beds",
    bedrooms: 4,
    beds: 12,
    businessHostLabel: null,
    city: "Provincia de Cartagena",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "15 guests",
    id: "49227437",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Provincia de Cartagena",
    localizedDistanceText: "3,684 miles",
    locationTitle: "Provincia de Cartagena, Bolívar",
    locationContext: null,
    listingName: "4BR Stunning Island in Blue Sea with Pool KALUA★",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Provincia de Cartagena, Bolívar, Colombia",
    reviews: null,
    reviewsCount: 3,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Island",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Provincia de Cartagena, Colombia",
    avgRatingLocalized: "5.0",
    accessibilityLabel: "$1,371 per night",
    concatQualifierLeft: false,
    price: "$1,371",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-01-07",
    checkout: "2023-01-12",
    relaxedAmenityIds: null,
    categoryTag: "Tag:675",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-49227437/original/7cf358b9-e8c5-4067-9ac5-014784387e22.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49227437/original/5b50ac57-8eca-4b8b-be51-43a7155ed37a.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49227437/original/df072e91-5a50-4c04-ac97-80aad69ec55d.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49227437/original/f1f4f807-b77f-4223-98f0-3afaa11520f6.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49227437/original/1db5e3c8-6149-460f-9f23-695d9dd7a468.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-49227437/original/9b06d931-4837-46b2-acc3-f5c4d44fc979.jpeg?im_w=720",
    ],
  },
  {
    avgRating: 5,
    listingBathroomLabel: "8 baths",
    bathrooms: 8,
    listingBedLabel: "10 beds",
    bedrooms: 6,
    beds: 10,
    businessHostLabel: null,
    city: "Cayos Cochinos",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "16 guests",
    id: "46604828",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Cayos Cochinos",
    localizedDistanceText: "2,921 miles",
    locationTitle: "Cayos Cochinos, Bay Islands Department",
    locationContext: null,
    listingName: "Luxury Round Cay in Cayos Cochinos, Bay Islands",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Cayos Cochinos, Bay Islands Department, Honduras",
    reviews: null,
    reviewsCount: 3,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Island",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Cayos Cochinos, Honduras",
    avgRatingLocalized: "5.0",
    accessibilityLabel: "$3,000 per night",
    concatQualifierLeft: false,
    price: "$3,000",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-03",
    checkout: "2022-12-08",
    relaxedAmenityIds: null,
    categoryTag: "Tag:675",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/a50d5639-bc18-45fa-af1b-48092414b6da.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/77b92395-baa6-4f1f-b9c4-93b073187539.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/2dc45145-111f-42f2-a481-3b32232b3381.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/b9764d08-083e-4073-842a-56c5488e4acc.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/e0ca96ec-597f-4ff2-9351-26bd14ec9d26.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a14c0d7b-52af-4772-ace7-b848da451532.jpg?im_w=720",
    ],
  },
  {
    avgRating: 5,
    listingBathroomLabel: "1 private bath",
    bathrooms: 1,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Bocas del Toro",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "24870403",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Bocas del Toro",
    localizedDistanceText: "3,474 miles",
    locationTitle: "Bocas del Toro, Bocas del Toro Province",
    locationContext: null,
    listingName: "Honeymooner’s Hut",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Bocas del Toro, Bocas del Toro Province, Panama",
    reviews: [],
    reviewsCount: 5,
    richKickers: null,
    roomType: "Private room",
    roomTypeCategory: "private_room",
    roomTypeId: null,
    spaceType: "Private room",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Bocas del Toro, Panama",
    avgRatingLocalized: "5.0",
    accessibilityLabel: "$275 per night",
    concatQualifierLeft: false,
    price: "$275",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-04",
    checkout: "2022-12-09",
    relaxedAmenityIds: null,
    categoryTag: "Tag:675",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/0e1e098c-1dcc-435c-99fc-288f6b06d7c8.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/361453a4-4e76-47dc-8ff4-e5491269669b.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/5a6c059c-1098-4bcd-84b1-11e4e02630a7.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/859c9d94-2d0c-4e71-97ef-534c6843133a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/b6422319-475c-4787-848b-47d4e238a1dd.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/68f94d1e-d468-46a1-ab4d-d5a16ab85bf9.jpg?im_w=720",
    ],
  },
  {
    avgRating: null,
    listingBathroomLabel: "5 baths",
    bathrooms: 5,
    listingBedLabel: "6 beds",
    bedrooms: 5,
    beds: 6,
    businessHostLabel: null,
    city: "Angra Dos Reis",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "12 guests",
    id: "39555598",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Angra Dos Reis",
    localizedDistanceText: "6,805 miles",
    locationTitle: "Angra Dos Reis, Rio De Janeiro",
    locationContext: null,
    listingName: "Beautiful private island with five spacious suites",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Angra Dos Reis, Rio De Janeiro, Brazil",
    reviews: null,
    reviewsCount: 0,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Villa",
    starRating: null,
    summary: null,
    wishlistedCount: null,
    title: "Angra Dos Reis, Brazil",
    avgRatingLocalized: null,
    accessibilityLabel: "$4,597 per night",
    concatQualifierLeft: false,
    price: "$4,597",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-02",
    checkout: "2022-12-09",
    relaxedAmenityIds: null,
    categoryTag: "Tag:675",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/3e37a3ee-6471-4356-b7ca-6856ab59b104.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/6eb5a54f-5453-468f-aa3f-dc4ca1b56281.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/263929de-f76f-4132-8198-c06b5efe0a25.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/352f9642-7529-4709-8e42-56b53ba35c59.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/fab66e13-c973-4084-b49c-582b82958f33.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/a34cb323-982d-423c-b8af-eb945f5d0b94.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.98,
    listingBathroomLabel: "1 bath",
    bathrooms: 1,
    listingBedLabel: "4 beds",
    bedrooms: 2,
    beds: 4,
    businessHostLabel: null,
    city: "Lac-Beauport",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "4 guests",
    id: "46695796",
    isAutoTranslated: true,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Lac-Beauport",
    localizedDistanceText: "2,416 miles",
    locationTitle: "Lac-Beauport, Quebec",
    locationContext: null,
    listingName: "MICA (Chalets Micro-Element) CITQ 303134",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Lac-Beauport, QC, Canada",
    reviews: [],
    reviewsCount: 168,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Tiny home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Lac-Beauport, Canada",
    avgRatingLocalized: "4.98",
    accessibilityLabel: "$296 per night",
    concatQualifierLeft: false,
    price: "$296",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-07-30",
    checkout: "2023-08-04",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-46695796/original/a0965aa5-3907-466e-b727-0900e2a7e8c7.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46695796/original/9bd67185-dc83-4473-a191-9486c62aec66.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46695796/original/088a6251-1a8c-459c-9f14-6d131fdb1a68.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-46695796/original/d01dc3d2-9597-4d88-92f7-3e15a1c0d604.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/f58c28d5-52d5-4c58-928e-ef00bf7164a3.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/9988b302-b51a-4765-ac74-da9dad0e326a.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.98,
    listingBathroomLabel: "Half-bath",
    bathrooms: 0.5,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Gaular",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "41004219",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Gaular",
    localizedDistanceText: "4,514 miles",
    locationTitle: "Gaular, Sogn og Fjordane",
    locationContext: null,
    listingName: "Breathtaking Mountain views in cozy Birdbox",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Gaular, Sogn og Fjordane, Norway",
    reviews: [],
    reviewsCount: 146,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Treehouse",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Gaular, Norway",
    avgRatingLocalized: "4.98",
    accessibilityLabel: "$352 per night",
    concatQualifierLeft: false,
    price: "$352",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-01",
    checkout: "2022-12-06",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/6721fc25-afe0-4f35-b181-212ec8ddc186.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/7a7f8828-57cc-4fa5-b7ff-ae06bf8409a9.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/23a60113-a16d-4cd6-bf5a-a2f352eb4f4e.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/4568c35b-bb8c-4367-b828-8f17bcea5934.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/1d22ab4c-641d-47d6-89fd-7c0418274ce7.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8ce649cd-a9fc-4c83-9c62-a75e31acc473.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.87,
    listingBathroomLabel: "2 baths",
    bathrooms: 2,
    listingBedLabel: "2 beds",
    bedrooms: 2,
    beds: 2,
    businessHostLabel: null,
    city: "Heredia",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "4 guests",
    id: "15378037",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Heredia",
    localizedDistanceText: "3,345 miles",
    locationTitle: "Heredia, Heredia",
    locationContext: null,
    listingName: "Alianz Loft",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Heredia, Heredia, Costa Rica",
    reviews: [],
    reviewsCount: 398,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Loft",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Heredia, Costa Rica",
    avgRatingLocalized: "4.87",
    accessibilityLabel: "$315 per night",
    concatQualifierLeft: false,
    price: "$315",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-18",
    checkout: "2022-12-23",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/2d8fd134-8d7c-4b69-a37e-17558908c426.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/eac3f9e7-316a-43d0-a988-20654e03d533.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/7a9506ba-f344-4f2e-a2b2-74ee881124fc.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/05c37d38-6d03-4789-b0cb-8192aeb331f4.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/7e1a0241-de29-4f86-88a4-725a89a2ca2e.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/fd615f4f-f8bc-44ea-a02b-a93a0d355ab1.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.8,
    listingBathroomLabel: "1 bath",
    bathrooms: 1,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Sindun-myeon, Icheon-si",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "45694252",
    isAutoTranslated: true,
    isNewListing: false,
    isSuperhost: false,
    relaxedFilterLabels: null,
    localizedCityName: "Sindun-myeon, Icheon-si",
    localizedDistanceText: "5,250 miles",
    locationTitle: "Sindun-myeon, Icheon-si, Gyeonggi-do",
    locationContext: null,
    listingName: "Emotional Healing in Lee Cheon-si, Seoul",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Sindun-myeon, Icheon-si, Gyeonggi-do, South Korea",
    reviews: [],
    reviewsCount: 131,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Cottage",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Sindun-myeon, Icheon-si, South Korea",
    avgRatingLocalized: "4.8",
    accessibilityLabel: "$68 per night",
    concatQualifierLeft: false,
    price: "$68",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-05",
    checkout: "2022-12-10",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/d0e3bb05-a96a-45cf-af92-980269168096.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/c2120b84-291d-4738-a911-97672d2ab3f2.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8db2283f-9f6c-4160-afb4-6f23b06c4217.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/5f5cb08f-c436-4ad3-8be7-325a2f54123f.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8bbe2dae-f9a5-4d5e-b682-5a8c2bc2231a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/c5469c7a-870a-4c2c-ad1a-5b4e57255285.jpg?im_w=720",
    ],
  },
  {
    avgRating: 4.95,
    listingBathroomLabel: "1 bath",
    bathrooms: 1,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Drimnin",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "19997279",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Drimnin",
    localizedDistanceText: "4,494 miles",
    locationTitle: "Drimnin, Scotland",
    locationContext: null,
    listingName: "Unique and Secluded AirShip with Breathtaking Highland Views",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Drimnin, Scotland, United Kingdom",
    reviews: [],
    reviewsCount: 327,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Tiny home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Drimnin, UK",
    avgRatingLocalized: "4.95",
    accessibilityLabel: "$198 per night",
    concatQualifierLeft: false,
    price: "$198",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-01-29",
    checkout: "2023-02-03",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: true,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/b7c9264d-73c9-45c3-882e-6e9577d63d68.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/a22e8b49-9e96-4da9-b5ab-6d7c63d191d6.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/4588d88f-0224-42f4-94cb-594f4d362fba.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/150e47d8-76b8-4233-8724-cbbd12880848.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/fceeaee2-bbe7-4ba8-b0b8-06863e70017a.jpg?im_w=1200",
      "https://a0.muscache.com/im/pictures/a855fd1a-7bee-4d8a-8c71-2e20e1647a20.jpg?im_w=1200",
    ],
  },
  {
    avgRating: 4.81,
    listingBathroomLabel: "1.5 shared baths",
    bathrooms: 1.5,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Pelkosenniemi",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "6 guests",
    id: "9386477",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Pelkosenniemi",
    localizedDistanceText: "4,500 miles",
    locationTitle: "Pelkosenniemi",
    locationContext: null,
    listingName: "Snow igloo",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Pelkosenniemi, Finland",
    reviews: [],
    reviewsCount: 123,
    richKickers: null,
    roomType: "Private room",
    roomTypeCategory: "private_room",
    roomTypeId: null,
    spaceType: "Private room",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Pelkosenniemi, Finland",
    avgRatingLocalized: "4.81",
    accessibilityLabel: "$135 per night",
    concatQualifierLeft: false,
    price: "$135",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-01-08",
    checkout: "2023-01-13",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/60d4058e-98a8-4f30-ba8a-93b101a31c47.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/61e15b47-a563-4348-b891-5106bc4ebb02.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/72e3dfea-2b90-4afe-a1bd-1be37e77539a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/126374d2-69b6-4695-887f-aeee6345e7f1.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/2a4637ae-4322-4623-9475-aad69250ba90.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/3b4e2e37-568c-40ed-8920-3ce71c3d99fc.jpg?im_w=720",
    ],
  },
  {
    avgRating: null,
    listingBathroomLabel: "2 baths",
    bathrooms: 2,
    listingBedLabel: "4 beds",
    bedrooms: 3,
    beds: 4,
    businessHostLabel: null,
    city: "Boulder",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "8 guests",
    id: "48246773",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Boulder",
    localizedDistanceText: "787 miles",
    locationTitle: "Boulder, Utah",
    locationContext: null,
    listingName: "Bedrock Homestead Full Cave",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Boulder, UT, United States",
    reviews: null,
    reviewsCount: 2,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Cave",
    starRating: null,
    summary: null,
    wishlistedCount: null,
    title: "Boulder, Utah",
    avgRatingLocalized: null,
    accessibilityLabel: "$950 per night",
    concatQualifierLeft: false,
    price: "$950",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2022-12-03",
    checkout: "2022-12-08",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/miso/Hosting-48246773/original/22a2c42e-108b-4809-b274-ada4f3d6da28.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48246773/original/e1cedb79-ae0b-487b-b604-185d39f3e264.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48246773/original/9f729f01-3ecd-4919-a74f-07b580d8b4d2.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48246773/original/286bb767-ea7f-4c9f-9162-4b0dee4740f0.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48246773/original/6e7cc096-ae8e-4307-88e7-b4ce5b1e9405.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-48246773/original/7a579bea-a788-441e-803a-b05f937f8332.jpeg?im_w=720",
    ],
  },
  {
    avgRating: 4.91,
    listingBathroomLabel: "3.5 baths",
    bathrooms: 3.5,
    listingBedLabel: "3 beds",
    bedrooms: 3,
    beds: 3,
    businessHostLabel: null,
    city: "Malibu",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "8 guests",
    id: "3156442",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Malibu",
    localizedDistanceText: "820 miles",
    locationTitle: "Malibu, California",
    locationContext: null,
    listingName: "EAGLE'S WATCH MALIBU- Architectural w/ Ocean View",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Malibu, CA, United States",
    reviews: [],
    reviewsCount: 11,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Home",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Malibu, California",
    avgRatingLocalized: "4.91",
    accessibilityLabel: "$1,495 per night",
    concatQualifierLeft: false,
    price: "$1,495",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-01-06",
    checkout: "2023-01-12",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/2e5ce6c9-4935-49ce-891e-e6f7251a8590.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/8cd65997-d77d-40f0-a41c-18ef2559d881.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/43016987-a5eb-47df-902d-a20960417fab.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-3156442/original/eceb2738-e46e-4ebb-8c74-99d9d5bbb82e.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-3156442/original/da7e5a4e-97b8-4ed2-86b7-3b4ebbfd3ecd.jpeg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-3156442/original/131f4eba-f3ab-4ef4-9ba8-12914179846e.jpeg?im_w=720",
    ],
  },
  {
    avgRating: 4.88,
    listingBathroomLabel: "Half-bath",
    bathrooms: 0.5,
    listingBedLabel: "1 bed",
    bedrooms: 1,
    beds: 1,
    businessHostLabel: null,
    city: "Forde",
    configurableContent: null,
    contextualPicturesPageInfo: {
      hasNextPage: true,
      endCursor: "NQ==",
    },
    emergencyMessage: null,
    listingFloatingMessage: null,
    formattedBadges: [],
    listingGuestLabel: "2 guests",
    id: "34692739",
    isAutoTranslated: false,
    isNewListing: false,
    isSuperhost: true,
    relaxedFilterLabels: null,
    localizedCityName: "Forde",
    localizedDistanceText: "4,508 miles",
    locationTitle: "Forde, Vestland fylke",
    locationContext: null,
    listingName: "Amazing view of fjord & mountains glamping Birdbox",
    listingObjType: "REGULAR",
    neighborhood: null,
    listingPreviewAmenityNames: [],
    previewTags: [],
    publicAddress: "Forde, Vestland fylke, Norway",
    reviews: [],
    reviewsCount: 303,
    richKickers: null,
    roomType: "Entire home/apt",
    roomTypeCategory: "entire_home",
    roomTypeId: null,
    spaceType: "Treehouse",
    starRating: 5,
    summary: null,
    wishlistedCount: null,
    title: "Forde, Norway",
    avgRatingLocalized: "4.88",
    accessibilityLabel: "$402 per night",
    concatQualifierLeft: false,
    price: "$402",
    qualifier: "night",
    trailingContent: null,
    adults: 1,
    children: 0,
    infants: 0,
    checkin: "2023-03-26",
    checkout: "2023-03-31",
    relaxedAmenityIds: null,
    categoryTag: "Tag:8225",
    pets: 0,
    verified: {
      enabled: false,
      badgeText: "Plus",
      badgeSecondaryText: "Verified",
      kickerBadgeType: "filled",
    },
    images: [
      "https://a0.muscache.com/im/pictures/c596d286-57a6-460e-b6a8-9698b6f31157.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/6df63a59-7ad7-4a4a-b28d-9796b5b97b0a.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/07baa603-c907-4d7e-9813-a6dddc734b77.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/42765c15-00bd-443b-9111-c13336bc2665.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/06af3372-d4b7-43c6-ad07-fd4883eb2b36.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/miso/Hosting-34692739/original/3a75ba1b-e9cb-4b93-b6eb-b757bbcbfa1e.jpeg?im_w=720",
    ],
  },
];

export default ordo;
